#!/bin/bash

apikeyreq=`curl -s -k -X GET 'https://10.217.16.203/api/?type=keygen&user=admin&password=Gee33025!'`

apikey2=${apikeyreq%"</key"*}
echo ${apikey2#*"key>"} > /var/www/paloalto/policyrules/apitest.txt

while [ $finalConfirmation = 'n' ]
