#!/bin/bash

echo
printf '\e[1;34m%-6s\e[m\n' "Configuration for dualog functionality"
printf '\e[1;34m%-6s\e[m\n' "You will need IP address for the Paloalto FW and credentials if default are not being used"
printf '\e[1;34m%-6s\e[m\n' "You will also need the IP address for the third interface (ens256) which will be use to coomunicate with Paloalto FW"
echo


finalConfirmation='n'
while [ $finalConfirmation = 'n' ]
do

############### Block to assign IP to the third interface #####################################
    correctIP='n'
    while [ $correctIP == 'n' ]
        do
            printf '\e[1;34m%-6s\e[m' "Please enter IP for third interface - ens256  (A.B.C.D/Z format) : "
            read dualogIpAddress 
            if [[ "$dualogIpAddress" != *"/"* ]]
            then
                printf '\e[1;31m%-6s\e[m\n' "It seems you didn't specify the subnet. Format needs to be A.B.C.D/Z. Please try again "
                #printf '\e[1;34m%-6s\e[m' "Enter native vlan IP for secondary interface (A.B.C.D/Z format) : "
                #read nativeIpAddress
            else
                correctIP='y'
            fi
        done

#########################################################################################################
echo
printf '\e[1;34m%-6s\e[m' "Enter Paloalto FW IP address (this is the address assigned to receive API calls - A.B.C.D format) "
read paloaltoIP

echo
printf '\e[1;34m%-6s\e[m\n' "Please review the info and confirm it is correct"
echo "PA interface (ens256) IP : "$dualogIpAddress
echo "Paloalto FW IP (Paloalto FW IP used to send API calls ) : $paloaltoIP"
printf '\e[1;34m%-6s\e[m' "Confirm (y/n)? "
read finalConfirmation
done   ########### finalconfirmation while  #################


############### interface file configuration with third interface ###########
printf '\e[1;34m%-6s\e[m\n' "Preparing configuration files"
echo
echo  >> /etc/network/interfaces
echo  >> /etc/network/interfaces
echo  "auto ens256" >> /etc/network/interfaces
echo  "iface ens256 inet static" >> /etc/network/interfaces
echo -e "\taddress $dualogIpAddress" >> /etc/network/interfaces
###################################################################################

########################## /etc/hosts file configuration
sed -i "s~X.Y.Z.P~${dualogIpAddress%/*}~g" /home/mtn/sampleFiles/hosts
sed -i "s~A.B.C.D~$paloaltoIP~g" /home/mtn/sampleFiles/hosts

echo
printf '\e[1;34m%-6s\e[m\n' "Setting configuration files in place"
cp /home/mtn/sampleFiles/hosts /etc/hosts
cp /home/mtn/sampleFiles/hostsTemplate /home/mtn/sampleFiles/hosts

echo
printf '\e[1;34m%-6s\e[m\n' "Requesting API key to Paloalto FW. Request is done using "


#apikeyreq=`curl -s -k -X GET 'https://10.217.16.203/api/?type=keygen&user=admin&password=Gee33025!'`

#apikey2=${apikeyreq%"</key"*}
#echo ${apikey2#*"key>"} > /var/www/paloalto/policyrules/apitest.txt





