#!/bin/bash
# 

printf '\e[1;34m%-6s\e[m\n' "Is default configuration with subnet 192.168.0.0/24 for FBB going to be applied (y/n)?"
read FBBOrig



if [[ "$FBBOrig" == 'n' ]]
then
	correctIP='n'
	while [ $correctIP == 'n' ]
		do
			printf '\e[1;34m%-6s\e[m' "Please enter FBB IP for third interface (A.B.C.D/Z format) "
			read  ipAddress
			if [[ "$ipAddress" != *"/"* ]]
			then
				printf '\e[1;31m%-6s\e[m\n' "It seems you didn't specify the subnet. Format needs to be A.B.C.D/Z. Please try again "
				#printf '\e[1;34m%-6s\e[m' "Enter native vlan IP for secondary interface (A.B.C.D/Z format) : "
				#read nativeIpAddress
			else
				correctIP='y'
			fi
		done
	printf '\e[1;34m%-6s\e[m' "Please enter FBB Default GW "
	read gwAddress
else
	ipAddress='192.168.0.120/24'  ###3  Static IPs assigned for FBB	
	gwAddress='192.168.0.1'
fi

echo "ip address:  "$ipAddress
echo "gw  :"$gwAddress