#!/bin/bash
if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root (do sudo vmconfiguration)"
	exit 1
fi
clear
printf '\e[1;32m%-6s\e[m\n' "Please select the option accordingly:"
printf '\e[1;34m%-6s\e[m\n' "1. Configure OBM Only (Three interfaces needed : Native Vlan1 , Management Vlan 2 , FBB)  "
printf '\e[1;34m%-6s\e[m\n' "2. Configure OBM + Dualog  (Five interfaces needed. Same interfaces as in 1. plus interfaces for PA connection. This interfaces
will be configured automatically) "
printf '\e[1;34m%-6s\e[m\n' "3. Get Paloalto API key. Needed if PA key was not obtained when #2 was ran the first time"
printf '\e[1;34m%-6s\e[m\n' "4. Activate SIEM system monitor (select if the solution includes SIEM option and after 1 or 2 has finished)"
read option


case $option in 

    1)
    obmconfiguration
    ;;

    2)
    dualog
    ;;

    3)
    apireq
    ;;
    4)
    siemconfig
    ;;
esac




